name: Deploy Node JS Simple

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.PORT }}" "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Package & Push
        run: |
          # Buat arsip di folder temp luar agar tidak terjadi 'file changed'
          tar -czf /tmp/app.tar.gz --exclude='.git' --exclude='node_modules' .
          
          # Kirim ke VPS
          scp -P "${{ secrets.PORT }}" /tmp/app.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/anonim-chat.tar.gz

      - name: Extract & Restart
        run: |
          ssh -p "${{ secrets.PORT }}" ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e
            # Load NVM agar npm/node terbaca
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Pastikan folder ada
            mkdir -p /var/www/anonim-chat
            cd /var/www/anonim-chat
            
            # Ekstrak file
            tar -xzf /var/www/anonim-chat.tar.gz -C .
            rm /var/www/anonim-chat.tar.gz
            
            # Install & Restart
            npm install --production
            pm2 restart anonim-chat || pm2 start index.js --name "anonim-chat"
          EOF