name: Deploy Node JS Laravel Style

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ssh key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.PORT }}" "${{ secrets.HOST }}" >> ~/.ssh/known_hosts

      - name: Package & Push
        run: |
          # Bungkus kode (abaikan node_modules)
          tar -czf app.tar.gz --exclude='node_modules' --exclude='.git' .
          
          # Kirim ke VPS (Laravel Style)
          scp -P "${{ secrets.PORT }}" app.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/anonim-chat.tar.gz

      - name: Extract & Restart
        run: |
          ssh -p "${{ secrets.PORT }}" ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            set -e
            export NVM_DIR=\"\$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"

            mkdir -p /var/www/anonim-chat
            cd /var/www/anonim-chat
            
            # Ekstrak file yang baru dikirim
            tar -xzf /var/www/anonim-chat.tar.gz -C .
            rm /var/www/anonim-chat.tar.gz
            
            # Install & Restart
            npm install --production
            pm2 restart anonim-chat || pm2 start index.js --name \"anonim-chat\"
          "